### PR TITLE
feat(serviceAccount): `GCP` service account shell script [ENG-44162]

### PR DESCRIPTION
**Pull request by tonygc**
This script creates the GCP roles and service account by using the `gcloud` CLI.

This `devops` PR explains what it does in a better way. [#157](https://github.com/drata/devops/pull/157).

Check this help article if needed https://help.drata.com/en/articles/4994112-gcp-connection-details.

The readme file looks like this

# gcp-shell-drata-setup

Shell script to create the Drata Read Only service account.

## Usage

The following steps demonstrate how to connect GCP in Drata when using this script.

1. Navigate to the Cloud Shell terminal in your GCP account using the following link: [https://console.cloud.google.com/welcome?cloudshell=true](https://console.cloud.google.com/welcome?cloudshell=true).
2. Click the `Open editor` button at the top of the terminal to navigate to your editor.
3. Create a file with `.sh` extension in the root directory i.e. `drata.sh`.
4. Copy the content of the `gcp-drata-script.sh` from this project and paste it in the newly created file.
5. Click the `Open terminal` button at the top of  the editor to navigate back to your terminal, run the following commands.
   1. `chmod +x drata.sh` to give it execution permissions.
   2. `./drata.sh` to run the script.
6. After the process finishes, navigate back to your editor and download the `drata-key-file.json` file.
7. In the Drata app, go to the GCP connection drawer and select Upload File to upload the `drata-key-file.json` file.
8. Select the `Save & Test Connection` button.

### CODE REVIEW

**Comment by AntonKDrata** [comment]
could you delete all terraform-related files from this repo in this PR?

**Comment by tonygc** [comment]
> could you delete all terraform-related files from this repo in this PR?

Sure 👍

**Review by Dwigth — APPROVED** [review]

**Comment by tonygc** [comment]
> could you delete all terraform-related files from this repo in this PR?

done! 🚀

**Comment by AntonKDrata** [comment]
Could you also change codeowners? or maybe remove it completely for now

**Comment by tonygc** [comment]
> Could you also change codeowners? or maybe remove it completely for now

Sure 👍

**Comment by tonygc** [comment]
> Could you also change codeowners? or maybe remove it completely for now

[done](https://github.com/drata/gcp-shell-drata-setup/pull/1/commits/9d42725b76ba82467be1e645df80e48d032aa6a9) 🚀

**Review by AngelRocaDrata — APPROVED** [review]

**Pull request merged**
